### PR TITLE
Automatic generation of script files based on known node versions

### PR DESCRIPTION
**Pull request by Grayda**
Not sure if you're interested in this, but I've written a gulpfile that retrieves a list of node versions and checks that an armv6l version exists, then generates the README and install scripts for those versions from a template.

I also added in a 'latest' script that parses the `/dist/latest` folder for the version number, then downloads that.

(Sorry for the fairly large number of 'fixing my untested mistakes' commits -- I was testing on my RPi remotely and copy / paste was fiddly)

### CODE REVIEW

**Comment by sdesalas** [comment]
Hi Grayda, thanks, this is awesome. Was thinking of getting a way to auto-generate these but you've saved me the trouble. Just need a chance to test on my pi zero before I merge in.

**Comment by KeesCBakker** [comment]
Any luck?

**Comment by sdesalas** [comment]
Hi Guys,

I added @Grayda fork as a link. Figured that as much as I want all the versions there it also makes it harder to get to the README content.

**Comment by Grayda** [comment]
Hi all, figured some of you might be interested in this: I've expanded that generation script to allow other architectures. 

I've published it as [node-installscripts](https://github.com/grayda/node-installscripts). It still works in much the same way, but now each architecture has its own README, and the scripts are bundled in folders.

My existing changes to `node-pi-zero` are still available, updated to include the latest versions as of yesterday.

**Pull request closed without merging**
